

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {

        initComponents();
        setSize(720,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radnrs = new javax.swing.JRadioButton();
        redwrs = new javax.swing.JRadioButton();
        redmbs = new javax.swing.JRadioButton();
        cbbp = new javax.swing.JCheckBox();
        cbp = new javax.swing.JCheckBox();
        cbc = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtsub = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txttax = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txttotal = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnen = new javax.swing.JButton();
        btnclr = new javax.swing.JButton();
        btnex = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.yellow);
        getContentPane().setLayout(null);

        radnrs.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        radnrs.setForeground(new java.awt.Color(255, 51, 51));
        radnrs.setText("Natural Raw Silk  Rs.5000");
        radnrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radnrsActionPerformed(evt);
            }
        });
        getContentPane().add(radnrs);
        radnrs.setBounds(30, 147, 210, 40);

        redwrs.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        redwrs.setForeground(new java.awt.Color(255, 51, 51));
        redwrs.setText("White Raw Silk Rs.7000");
        redwrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redwrsActionPerformed(evt);
            }
        });
        getContentPane().add(redwrs);
        redwrs.setBounds(33, 199, 210, 20);

        redmbs.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        redmbs.setForeground(new java.awt.Color(255, 51, 51));
        redmbs.setText("Mulberry Silk Rs.9500");
        redmbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redmbsActionPerformed(evt);
            }
        });
        getContentPane().add(redmbs);
        redmbs.setBounds(33, 267, 220, 20);

        cbbp.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        cbbp.setText("Box Packed  Rs.125");
        getContentPane().add(cbbp);
        cbbp.setBounds(458, 134, 230, 26);

        cbp.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        cbp.setText("Packed Rs.115");
        cbp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpActionPerformed(evt);
            }
        });
        getContentPane().add(cbp);
        cbp.setBounds(460, 190, 180, 26);

        cbc.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        cbc.setText("Colored Rs.50");
        getContentPane().add(cbc);
        cbc.setBounds(460, 260, 210, 26);

        jScrollPane1.setViewportView(txtsub);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(492, 341, 109, 22);

        jScrollPane2.setViewportView(txttax);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(495, 381, 109, 22);

        jScrollPane3.setViewportView(txttotal);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(495, 421, 109, 22);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel2.setText("TAX");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 380, 132, 22);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel3.setText("SUBTOTAL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(327, 337, 100, 22);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        jLabel4.setText("TOTAL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 420, 140, 30);

        btnen.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnen.setText("ENTER");
        btnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenActionPerformed(evt);
            }
        });
        getContentPane().add(btnen);
        btnen.setBounds(33, 334, 150, 29);

        btnclr.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnclr.setText("CLEAR");
        btnclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclrActionPerformed(evt);
            }
        });
        getContentPane().add(btnclr);
        btnclr.setBounds(33, 381, 150, 29);

        btnex.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnex.setText("EXIT");
        btnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexActionPerformed(evt);
            }
        });
        getContentPane().add(btnex);
        btnex.setBounds(30, 430, 150, 29);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SILK MERCHANDISE RECKONER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 630, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\uzair\\Desktop\\s5.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-30, 0, 730, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radnrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radnrsActionPerformed
            // TODO add your handling code here:
            if(radnrs.isSelected())
            {
                redwrs.setSelected(false);
                redmbs.setSelected(false);
            }
                
    }//GEN-LAST:event_radnrsActionPerformed

    private void cbpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpActionPerformed
        // TODO add your handling code hersd
    }//GEN-LAST:event_cbpActionPerformed

    private void redwrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redwrsActionPerformed
        // TODO add your handling code here:
        if(redwrs.isSelected())
        {radnrs.setSelected(false);
                redmbs.setSelected(false);}
    }//GEN-LAST:event_redwrsActionPerformed

    private void redmbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redmbsActionPerformed
        // TODO add your handling code here:
        if(redmbs.isSelected())
        {radnrs.setSelected(false);
                redwrs.setSelected(false);}
    }//GEN-LAST:event_redmbsActionPerformed

    private void btnenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenActionPerformed
        // TODO add your handling code here:
       // DecimalFormat df = new DecimalFormat("0.00")
        double total;
        double subtotal=0;
        final double TAXRATE = .18;
        double tax;
        
        if(radnrs.isSelected()){
              subtotal = subtotal + 5000 ;
    }
        else if (redmbs.isSelected()){
                subtotal = subtotal + 9500;
    }
            
        else if (redwrs.isSelected()){
                subtotal = subtotal + 7000;
    }
        
        if(cbbp.isSelected()){
             subtotal = subtotal + 125 ;
           
        }if(cbc.isSelected()){
             subtotal = subtotal + 115 ;
           
        }if(cbp.isSelected()){
             subtotal = subtotal + 50 ;
           
        }
        
        txtsub.setText(Double.toString(subtotal));
        subtotal = Double.parseDouble(txtsub.getText());
        tax = subtotal * TAXRATE;
        total = tax + subtotal;
        
        txttax.setText(Double.toString(tax));
        txttotal.setText(Double.toString(total));
        
       // txttax.setText(df.format (tax));
       // txtsub.setText(df.format (subtotal));
        //txttotal.setText(df.format (total));
        
    }//GEN-LAST:event_btnenActionPerformed

    private void btnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexActionPerformed

    private void btnclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclrActionPerformed
        // TODO add your handling code here:
        radnrs.setSelected(false);
        redmbs.setSelected(false);
        redwrs.setSelected(false);
        cbbp.setSelected(false);
        cbc.setSelected(false);
        cbp.setSelected(false);
        txtsub.setText("");
        txttax.setText("");
        txttotal.setText("");
    }//GEN-LAST:event_btnclrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
 
                new NewJFrame().setVisible(true);
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclr;
    private javax.swing.JButton btnen;
    private javax.swing.JButton btnex;
    private javax.swing.JCheckBox cbbp;
    private javax.swing.JCheckBox cbc;
    private javax.swing.JCheckBox cbp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radnrs;
    private javax.swing.JRadioButton redmbs;
    private javax.swing.JRadioButton redwrs;
    private javax.swing.JTextPane txtsub;
    private javax.swing.JTextPane txttax;
    private javax.swing.JTextPane txttotal;
    // End of variables declaration//GEN-END:variables
}
